Allow manual setting of answer
KojinKuro/ludole pull request #28
Opened 2024-05-28 22:49 UTC by KojinKuro

# Description

Allow manual setting of a ludole answer.

## Context

- Allow manual setting of the correct answer by adding `answerIndex` as a prop for any `<GamePage />` component. The `answerIndex` will default to being random if none is given (which is how we had it before). `answerIndex` must be from 0 to `games.length`. This allows us to manually set what games we are checking, and what the answer is by passing them in as props.
- Remove old comments for features outside of MVP.
- Added back in search bar button due to Cypress testing expecting it to exist.

Fixes #25 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This code does not have any Cypress testing done will be done as part of the #27 task. Manual testing was done by changing the `<GamePage />` route in `App.jsx` to have a prop of `answerIndex={someNumber}`. The `answerIndex` will set the answer of the ludole to always be the game at `answerIndex` index position of the `games` array.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-05-28 23:20 UTC, moth-dust requested changes

2024-05-28 23:20 UTC, moth-dust commented on src/pages/GamePage.jsx
This does allow for us to change the answer by hard coding it, but cypress doesn't have access to values like this other than via intercept so actually leveraging it would require us to have some sort of clickable element or path that loads the game differently, or just to have a commented line in App that contains a hard coded answer with a note about it in the test files. This request can be dismissed is there is no preference between those options, and it can be handled when the tests are written.

2024-05-29 00:50 UTC, KojinKuro commented on src/pages/GamePage.jsx
Intercepting is possible if we add more to the backend, but we have already decided this is outside of the MVP.

I think between having a debug URL and a clickable dev element, the URL is better. We can create a new route with a url of `localhost:5173/test` and run the Cypress test there. We would not include this url anywhere and it would only be used for testing. This would be a good balance of keeping a URL we could test while keeping it "hidden" from the user.

I do not like the clickable (assumedly hidden) element button  given that a user might accidentally click it and find our hidden dev route.

2024-05-29 00:57 UTC, moth-dust commented on src/pages/GamePage.jsx
Yeah sounds good! I will implement this when writing the tests and mark as resolved.

2024-05-29 00:59 UTC, moth-dust approved these changes
Changes discussed and marked resolved.

2024-05-29 03:10 UTC, merged